root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/inference-gateway"
  cmd = "go build -o ./tmp/inference-gateway ./cmd/server"
  delay = 500
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true
